site_name: Studio Controls
theme:
  name: material
  palette:
  - scheme: default   # Light mode
    primary: green
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  - scheme: slate     # Dark mode
    primary: green
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  features:
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.instant.progress
      - navigation.tabs 
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.path
      - navigation.indexes
      - navigation.top
      - navigation.footer
      - header.autohide
      - search.suggest
      - search.highlight
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - attr_list

extra_css:
  - docsAssets/style.css

nav:
  - Home: index.md
  - Fundamentals:
      - Get Started: Fundamentals/get-started.md
      - Your First Controller: Fundamentals/your-first-controller.md