site_name: Studio Controls
theme:
  name: material
  palette:
    - toggle:
      scheme: slate
  features:
    - navigation.top
    - header.autohide
    - navigation.sections
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - attr_list

extra_css:
  - docsAssets/style.css

extra_javascript:
  - https://kit.fontawesome.com/YOUR_KIT_CODE.js